#ifndef CUTILS_CONFIG_H
#define CUTILS_CONFIG_H

/* Memory Management Configuration */
#define CUTILS_USE_STATIC_ALLOCATION 1
#define CUTILS_USE_DYNAMIC_ALLOCATION 0
#define CUTILS_MAX_STATIC_MEMORY (64 * 1024) // 64KB
#define CUTILS_ALIGNMENT 8

/* Real-Time Configuration */
#define CUTILS_MAX_OPERATION_TIME_MS 1
#define CUTILS_USE_PRIORITY_QUEUE 1
#define CUTILS_MAX_PRIORITY_LEVELS 8

/* Safety Features */
#define CUTILS_ENABLE_ASSERTIONS 1
#define CUTILS_ENABLE_BOUNDS_CHECKING 1
#define CUTILS_ENABLE_OVERFLOW_CHECKING 1
#define CUTILS_ENABLE_NULL_PTR_CHECKING 1

/* Platform Configuration */
#define CUTILS_PLATFORM_BARE_METAL 1
#define CUTILS_ENDIANNESS_LITTLE 1
#define CUTILS_USE_CUSTOM_ALLOCATOR 1

/* Feature Flags */
#define CUTILS_ENABLE_THREAD_SAFETY 0
#define CUTILS_ENABLE_EXCEPTIONS 0
#define CUTILS_ENABLE_LOGGING 1

/* Error Handling */
#define CUTILS_USE_ERROR_CODES 1
#define CUTILS_MAX_ERROR_STRING_LEN 64

/* Vector Configuration */
#define CUTILS_VECTOR_INIT_CAPACITY 16
#define CUTILS_VECTOR_MAX_CAPACITY 1024
#define CUTILS_VECTOR_GROWTH_FACTOR 2

/* Arena Configuration */
#define CUTILS_ARENA_DEFAULT_BLOCK_SIZE 1024
#define CUTILS_ARENA_MAX_BLOCKS 16

#endif /* CUTILS_CONFIG_H */